[settings]
allow_nsfw = false
theme = "light"
times_to_run = 1
opacity = 0.9
storymode = false

[reddit.creds]
client_id = "adsfadsfasdf"
client_secret = "adsfasdfadsfasdfasdf"
username = "asdfasdfadsf"
password = "asdfasdfadsf"
2fa = false

[reddit.thread]
random = false
subreddit = "asdfasdfadsfadsfadfs"
post_id = "asdfasdfasdf"
max_comment_length = 500
